### ISSUE TITLE
Arelle Repo Dockerfile

### ISSUE THREAD

**Issue by campbelldgunn** [seocahill/taxonomy-parser#1]
Hi @seocahill ,

Sorry for posting the issue here. But I could not create an issue on the forked Arelle repo that you had. I notice that you have a docker container on Arelle, would you mind sharing the dockerfile?

Thanks in Advance.

Campbell

**Comment by seocahill** [comment]
Hi Campbell you want this one I'd say

https://github.com/seocahill/arelle-web-service/blob/master/Dockerfile

**Comment by campbelldgunn** [comment]
Thank you. Much appreciated. I now need to add the Edgar Renderer as a plugin as well to the Dockerfile. Cheers!
